services:
  - type: web
    name: proxy-browser
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX
        sync: false
